# Generated by Django 4.1.1 on 2022-09-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
