# Generated by Django 4.1.1 on 2022-09-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(None, 'SELECT'), (0, 'Pending Order'), (1, 'Order Accepted'), (2, 'Perparing Food'), (3, 'Food On The Way'), (4, 'Delivered')], default=0, verbose_name='StatusType'),
        ),
    ]
