# Generated by Django 4.1.2 on 2022-11-09 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='checksum',
        ),
    ]
