# Generated by Django 4.1.2 on 2022-11-09 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_transaction_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='paid',
        ),
    ]
